// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOfflineAccount(arg1) {
  return window['go']['main']['App']['AddOfflineAccount'](arg1);
}

export function DownloadVersion(arg1) {
  return window['go']['main']['App']['DownloadVersion'](arg1);
}

export function EnableTestMode() {
  return window['go']['main']['App']['EnableTestMode']();
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetActiveAccount() {
  return window['go']['main']['App']['GetActiveAccount']();
}

export function GetSystemPlatform() {
  return window['go']['main']['App']['GetSystemPlatform']();
}

export function LaunchGame(arg1, arg2) {
  return window['go']['main']['App']['LaunchGame'](arg1, arg2);
}

export function SetActiveAccount(arg1) {
  return window['go']['main']['App']['SetActiveAccount'](arg1);
}
