// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';
import {instances} from '../models';
import {settings} from '../models';
import {system} from '../models';
import {models} from '../models';
import {javascanner} from '../models';

export function AddOfflineAccount(arg1:string):Promise<auth.Account>;

export function CancelDownload():Promise<void>;

export function CreateInstance(arg1:string,arg2:string,arg3:string,arg4:string):Promise<instances.Instance>;

export function DeleteInstance(arg1:string):Promise<void>;

export function DownloadVersion(arg1:string):Promise<void>;

export function EnableTestMode():Promise<void>;

export function GetAccounts():Promise<Array<auth.Account>>;

export function GetActiveAccount():Promise<auth.Account>;

export function GetFabricLoaders(arg1:string):Promise<Array<string>>;

export function GetInstances():Promise<Array<instances.Instance>>;

export function GetQuiltLoaders(arg1:string):Promise<Array<string>>;

export function GetSettings():Promise<settings.LauncherSettings>;

export function GetSystemPlatform():Promise<system.SystemInfo>;

export function GetVanillaVersions():Promise<Array<models.Version>>;

export function LaunchInstance(arg1:string):Promise<void>;

export function LoginElyBy(arg1:string,arg2:string):Promise<auth.Account>;

export function OpenInstanceFolder(arg1:string):Promise<void>;

export function ScanJavaInstallations():Promise<Array<javascanner.JavaInfo>>;

export function SetActiveAccount(arg1:string):Promise<void>;

export function StartInstanceDownload(arg1:string):Promise<void>;

export function StopInstance(arg1:string):Promise<void>;

export function UpdateGlobalSettings(arg1:settings.LauncherSettings):Promise<void>;

export function UpdateInstanceSettings(arg1:string,arg2:instances.InstanceSettings):Promise<void>;
