// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';
import {system} from '../models';

export function AddOfflineAccount(arg1:string):Promise<auth.Account>;

export function DownloadVersion(arg1:string):Promise<void>;

export function EnableTestMode():Promise<void>;

export function GetAccounts():Promise<Array<auth.Account>>;

export function GetActiveAccount():Promise<auth.Account>;

export function GetSystemPlatform():Promise<system.SystemInfo>;

export function LaunchGame(arg1:string,arg2:number):Promise<void>;

export function SetActiveAccount(arg1:string):Promise<void>;
