// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOfflineAccount(arg1) {
  return window['go']['main']['App']['AddOfflineAccount'](arg1);
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CreateInstance(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateInstance'](arg1, arg2, arg3, arg4);
}

export function DeleteInstance(arg1) {
  return window['go']['main']['App']['DeleteInstance'](arg1);
}

export function DownloadVersion(arg1) {
  return window['go']['main']['App']['DownloadVersion'](arg1);
}

export function EnableTestMode() {
  return window['go']['main']['App']['EnableTestMode']();
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetActiveAccount() {
  return window['go']['main']['App']['GetActiveAccount']();
}

export function GetFabricLoaders(arg1) {
  return window['go']['main']['App']['GetFabricLoaders'](arg1);
}

export function GetInstances() {
  return window['go']['main']['App']['GetInstances']();
}

export function GetQuiltLoaders(arg1) {
  return window['go']['main']['App']['GetQuiltLoaders'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemPlatform() {
  return window['go']['main']['App']['GetSystemPlatform']();
}

export function GetVanillaVersions() {
  return window['go']['main']['App']['GetVanillaVersions']();
}

export function LaunchInstance(arg1) {
  return window['go']['main']['App']['LaunchInstance'](arg1);
}

export function LoginElyBy(arg1, arg2) {
  return window['go']['main']['App']['LoginElyBy'](arg1, arg2);
}

export function OpenInstanceFolder(arg1) {
  return window['go']['main']['App']['OpenInstanceFolder'](arg1);
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function ScanJavaInstallations() {
  return window['go']['main']['App']['ScanJavaInstallations']();
}

export function SetActiveAccount(arg1) {
  return window['go']['main']['App']['SetActiveAccount'](arg1);
}

export function StartInstanceDownload(arg1) {
  return window['go']['main']['App']['StartInstanceDownload'](arg1);
}

export function StopInstance(arg1) {
  return window['go']['main']['App']['StopInstance'](arg1);
}

export function UpdateGlobalSettings(arg1) {
  return window['go']['main']['App']['UpdateGlobalSettings'](arg1);
}

export function UpdateInstanceSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdateInstanceSettings'](arg1, arg2);
}
