// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadVersion(arg1) {
  return window['go']['main']['App']['DownloadVersion'](arg1);
}

export function EnableTestMode() {
  return window['go']['main']['App']['EnableTestMode']();
}

export function GetSystemPlatform() {
  return window['go']['main']['App']['GetSystemPlatform']();
}

export function LaunchGame(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchGame'](arg1, arg2, arg3);
}
