// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {system} from '../models';

export function DownloadVersion(arg1:string):Promise<void>;

export function EnableTestMode():Promise<void>;

export function GetSystemPlatform():Promise<system.SystemInfo>;

export function LaunchGame(arg1:string,arg2:number,arg3:string):Promise<void>;
